import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AuthProvider from "./context/AuthProvider";
import Footer from "./components/navigation/Footer";
import Sidebar from "./components/navigation/Sidebar";
import Navbar from "./components/navigation/Navbar";
import TopBar from "./components/navigation/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="bg-primary text-white flex max-w-[1920px] mx-auto"
      >
        <AuthProvider>
          {" "}
          <div className="flex-1 bg-secondary p-5 min-h-screen max-lg:hidden">
            <Sidebar />
          </div>
          <div className="flex-[4_4_0%] md:p-5 flex flex-col justify-between h-screen ">
            <Navbar />
            <TopBar />
            {children}
            <Toaster richColors />
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
